[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "Ens7Gx99whnA8zZm6ZiFnWgGq3x76nXbSmh5gaaJqpAz"
autocrat_migrator = "MigRDW6uxyNMDBD8fX2njCRyJC4YZk2Rx9pDUZiAESt"
autocrat = "FuTPR6ScKMPHtZFwacq9qrtf9VjscawNEFTb2wSYr1gY"
conditional_vault = "vAuLTQjV5AZx5f3UgE75wcnkxnQowWxThn1hGjfCVwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
airdrop = "yarn run ts-node scripts/airdrop.ts"
autocrat_v0 = "yarn run ts-node scripts/autocratV0.ts"
clob = "yarn run tsc scripts/clob.ts --esModuleInterop --resolveJsonModule && node scripts/clob.js && rm scripts/clob.js"
crank = "yarn run ts-node scripts/crank.ts"
crank_twap = "yarn run ts-node scripts/crankTwap.ts"
initialize_dao = "yarn run ts-node scripts/initializeDao.ts"
initialize_vault = "yarn run tsc scripts/initializeVault.ts --esModuleInterop --resolveJsonModule && node scripts/initializeVault.js"
main = "yarn run ts-node scripts/main.ts"
multisig = "yarn run tsx scripts/multisig.ts"
place_order = "yarn run ts-node scripts/placeOrder.ts"
propose = "yarn run ts-node scripts/initializeProposal.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb"
program = "./tests/fixtures/openbook_v2.so"

[[test.genesis]]
address = "TWAP7frdvD3ia7TWc8e9SxZMmrpd2Yf3ifSPAHS8VG3"
program = "./tests/fixtures/openbook_twap.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/fixtures/mpl_token_metadata.so"
